import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;

import org.junit.jupiter.api.Test;

import TAB_TO_XML.App;

class AppTest {
	
	@Test
	public void getFileListTest1() {
		String text = "Hello\nWorld\nOut\nThere";
		ArrayList<String> actual = App.getFileList(text);
		ArrayList<String> expected = new ArrayList<String>();
		expected.add("Hello");
		expected.add("World");
		expected.add("Out");
		expected.add("There");
		
		assertEquals(expected, actual);
	}
	
	@Test
	public void getFileListTest2() {
		String text = "This";
		ArrayList<String> actual = App.getFileList(text);
		ArrayList<String> expected = new ArrayList<String>();
		expected.add("This");
		
		assertEquals(expected, actual);
	}
	
	@Test
	public void getFileListTest3() {
		String text = "|-----------0-----|-0---------------|\n"
				+ "|---------0---0---|-0---------------|\n"
				+ "|-------1-------1-|-1---------------|\n"
				+ "|-----2-----------|-2---------------|\n"
				+ "|---2-------------|-2---------------|\n"
				+ "|-0---------------|-0---------------|\n"
				+ "\n"
				+ "|-----------0-----|-0---------------|\n"
				+ "|---------0---0---|-0---------------|\n"
				+ "|-------1-------1-|-1---------------|\n"
				+ "|-----2-----------|-2---------------|\n"
				+ "|---2-------------|-2---------------|\n"
				+ "|-0---------------|-0---------------|\n"
				+ "\n"
				+ "|-----------0-----|-0---------------|\n"
				+ "|---------0---0---|-0---------------|\n"
				+ "|-------1-------1-|-1---------------|\n"
				+ "|-----2-----------|-2---------------|\n"
				+ "|---2-------------|-2---------------|\n"
				+ "|-0---------------|-0---------------|";
		ArrayList<String> actual = App.getFileList(text);
		ArrayList<String> expected = new ArrayList<>();
		expected.add("|-----------0-----|-0---------------|");
		expected.add("|---------0---0---|-0---------------|");
		expected.add("|-------1-------1-|-1---------------|");
		expected.add("|-----2-----------|-2---------------|");
		expected.add("|---2-------------|-2---------------|");
		expected.add("|-0---------------|-0---------------|");
		expected.add("");
		expected.add("|-----------0-----|-0---------------|");
		expected.add("|---------0---0---|-0---------------|");
		expected.add("|-------1-------1-|-1---------------|");
		expected.add("|-----2-----------|-2---------------|");
		expected.add("|---2-------------|-2---------------|");
		expected.add("|-0---------------|-0---------------|");
		expected.add("");
		expected.add("|-----------0-----|-0---------------|");
		expected.add("|---------0---0---|-0---------------|");
		expected.add("|-------1-------1-|-1---------------|");
		expected.add("|-----2-----------|-2---------------|");
		expected.add("|---2-------------|-2---------------|");
		expected.add("|-0---------------|-0---------------|");
		
		assertEquals(expected, actual);
	}

	@Test
	public void identifyInstrumentTest1() {
		ArrayList<String> guitarTab = new ArrayList<>();
		guitarTab.add("|-----------0-----|-0---------------|");
		guitarTab.add("|---------0---0---|-0---------------|");
		guitarTab.add("|-------1-------1-|-1---------------|");
		guitarTab.add("|-----2-----------|-2---------------|");
		guitarTab.add("|---2-------------|-2---------------|");
		guitarTab.add("|-0---------------|-0---------------|");
		guitarTab.add("");
		guitarTab.add("|-----------0-----|-0---------------|");
		guitarTab.add("|---------0---0---|-0---------------|");
		guitarTab.add("|-------1-------1-|-1---------------|");
		guitarTab.add("|-----2-----------|-2---------------|");
		guitarTab.add("|---2-------------|-2---------------|");
		guitarTab.add("|-0---------------|-0---------------|");
		guitarTab.add("");
		guitarTab.add("|-----------0-----|-0---------------|");
		guitarTab.add("|---------0---0---|-0---------------|");
		guitarTab.add("|-------1-------1-|-1---------------|");
		guitarTab.add("|-----2-----------|-2---------------|");
		guitarTab.add("|---2-------------|-2---------------|");
		guitarTab.add("|-0---------------|-0---------------|");
		String actual = App.identifyInstrument(guitarTab);
		String expected = "Guitar";
		assertEquals(expected, actual);
	}
	
	@Test
	public void identifyInstrumentTest2() {
		ArrayList<String> drumTab = new ArrayList<>();
		drumTab.add("CC|x---------------|--------x-------|");
		drumTab.add("HH|--x-x-x-x-x-x-x-|----------------|");
		drumTab.add("SD|----o-------o---|oooo------------|");
		drumTab.add("HT|----------------|----oo----------|");
		drumTab.add("MT|----------------|------oo--------|");
		drumTab.add("BD|o-------o-------|o-------o-------|");
		String actual = App.identifyInstrument(drumTab);
		String expected = "Drums";
		assertEquals(expected, actual);
	}
	
	@Test
	public void identifyInstrumentTest3() {
		ArrayList<String> bassTab = new ArrayList<>();
		bassTab.add("G |--------7-----------|");
		bassTab.add("D |--------------------|");
		bassTab.add("A |--------------------|");
		bassTab.add("E |-/5--7-----7--5--7--|");
		bassTab.add("");
		bassTab.add("G |--------7-----------|");
		bassTab.add("D |--------------------|");
		bassTab.add("A |--------------------|");
		bassTab.add("E |-/5--7-----7--5--7--|");
		bassTab.add("");
		bassTab.add("G |--------7-----------|");
		bassTab.add("D |--------------------|");
		bassTab.add("A |--------------------|");
		bassTab.add("E |-/5--7-----7--5--7--|");
		String actual = App.identifyInstrument(bassTab);
		String expected = "Bass";
		assertEquals(expected, actual);
	}
	
	@Test
	public void identifyInstrumentTest4() {
		ArrayList<String> guitarTab = new ArrayList<>();
		guitarTab.add("CC|-----------x-----|-0---------------|");
		guitarTab.add("HH|---------0---0---|-0---------------|");
		guitarTab.add("SD|-------1-------1-|-1---------------|");
		guitarTab.add("HT|-----2-----------|-2---------------|");
		guitarTab.add("MT|---2-------------|-2---------------|");
		guitarTab.add("BD|-0---------------|-0---------------|");
		String actual = App.identifyInstrument(guitarTab);
		String expected = "Guitar";
		assertEquals(expected, actual);
	}
	
	@Test
	public void guitarTabToXMLTest1() {
		ArrayList<String> tabAsList = App.getFileList(
				"|-----------0-----|-0---------------|\n"
				+ "|---------0---0---|-0---------------|\n"
				+ "|-------1-------1-|-1---------------|\n"
				+ "|-----2-----------|-2---------------|\n"
				+ "|---2-------------|-2---------------|\n"
				+ "|-0---------------|-0---------------|");
		String actual = App.guitarTabToXML(tabAsList);
		String expected = "<score-partwise version=\"3.1\">\n"
				+ "  <part-list>\n"
				+ "    <score-part id=\"P1\">\n"
				+ "      <part-name>Classical Guitar</part-name>\n"
				+ "    </score-part>\n"
				+ "  </part-list>\n"
				+ "  <part id=\"P1\">\n"
				+ "    <measure number=\"1\">\n"
				+ "      <attributes>\n"
				+ "        <divisions>2</divisions>\n"
				+ "        <key>\n"
				+ "          <fifths>0</fifths>\n"
				+ "        </key>\n"
				+ "        <time>\n"
				+ "          <beats>4</beats>\n"
				+ "          <beat-type>4</beat-type>\n"
				+ "        </time>\n"
				+ "        <clef>\n"
				+ "          <sign>TAB</sign>\n"
				+ "          <line>5</line>\n"
				+ "        </clef>\n"
				+ "        <staff-details>\n"
				+ "          <staff-lines>6</staff-lines>\n"
				+ "          <staff-tuning line=\"1\">\n"
				+ "            <tuning-step>E</tuning-step>\n"
				+ "            <tuning-octave>2</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "          <staff-tuning line=\"2\">\n"
				+ "            <tuning-step>A</tuning-step>\n"
				+ "            <tuning-octave>2</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "          <staff-tuning line=\"3\">\n"
				+ "            <tuning-step>D</tuning-step>\n"
				+ "            <tuning-octave>3</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "          <staff-tuning line=\"4\">\n"
				+ "            <tuning-step>G</tuning-step>\n"
				+ "            <tuning-octave>3</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "          <staff-tuning line=\"5\">\n"
				+ "            <tuning-step>B</tuning-step>\n"
				+ "            <tuning-octave>3</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "          <staff-tuning line=\"6\">\n"
				+ "            <tuning-step>E</tuning-step>\n"
				+ "            <tuning-octave>4</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "        </staff-details>\n"
				+ "      </attributes>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>E</step>\n"
				+ "          <octave>2</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>6</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>B</step>\n"
				+ "          <octave>2</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>5</string>\n"
				+ "            <fret>2</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>E</step>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>4</string>\n"
				+ "            <fret>2</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>G</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>3</string>\n"
				+ "            <fret>1</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>B</step>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>2</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>E</step>\n"
				+ "          <octave>4</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>1</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>B</step>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>2</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>G</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>3</string>\n"
				+ "            <fret>1</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "    </measure>\n"
				+ "    <measure number=\"2\">\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>E</step>\n"
				+ "          <octave>2</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>8</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>whole</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>6</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>B</step>\n"
				+ "          <octave>2</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>8</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>whole</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>5</string>\n"
				+ "            <fret>2</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>E</step>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>8</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>whole</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>4</string>\n"
				+ "            <fret>2</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>G</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>8</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>whole</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>3</string>\n"
				+ "            <fret>1</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>B</step>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>8</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>whole</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>2</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>E</step>\n"
				+ "          <octave>4</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>8</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>whole</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>1</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <barline location=\"right\">\n"
				+ "        <bar-style>light-heavy</bar-style>\n"
				+ "      </barline>\n"
				+ "    </measure>\n"
				+ "  </part>\n"
				+ "</score-partwise>\n"
				+ "";
		
		// remove whitespace characters
		actual = actual.replaceAll("\\s+","");
		expected = expected.replaceAll("\\s+","");
		
		assertEquals(expected, actual);
	}
	
	@Test
	public void guitarTabToXMLTest2() {
		ArrayList<String> tabAsList = App.getFileList(
				"|-----------0-----|-0---------------|\n"
				+ "|---------0---0---|-0---------------|\n"
				+ "|-------1-------1-|-1---------------|\n"
				+ "|-----2-----------|-2---------------|\n"
				+ "|---2-------------|-2---------------|\n"
				+ "|-0---------------|-0---------------|\n"
				+ "\n"
				+ "|-----------0-----|-0---------------|\n"
				+ "|---------0---0---|-0---------------|\n"
				+ "|-------1-------1-|-1---------------|\n"
				+ "|-----2-----------|-2---------------|\n"
				+ "|---2-------------|-2---------------|\n"
				+ "|-0---------------|-0---------------|");
		String actual = App.guitarTabToXML(tabAsList);
		String expected = "<score-partwise version=\"3.1\">\n"
				+ "  <part-list>\n"
				+ "    <score-part id=\"P1\">\n"
				+ "      <part-name>Classical Guitar</part-name>\n"
				+ "    </score-part>\n"
				+ "  </part-list>\n"
				+ "  <part id=\"P1\">\n"
				+ "    <measure number=\"1\">\n"
				+ "      <attributes>\n"
				+ "        <divisions>2</divisions>\n"
				+ "        <key>\n"
				+ "          <fifths>0</fifths>\n"
				+ "        </key>\n"
				+ "        <time>\n"
				+ "          <beats>4</beats>\n"
				+ "          <beat-type>4</beat-type>\n"
				+ "        </time>\n"
				+ "        <clef>\n"
				+ "          <sign>TAB</sign>\n"
				+ "          <line>5</line>\n"
				+ "        </clef>\n"
				+ "        <staff-details>\n"
				+ "          <staff-lines>6</staff-lines>\n"
				+ "          <staff-tuning line=\"1\">\n"
				+ "            <tuning-step>E</tuning-step>\n"
				+ "            <tuning-octave>2</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "          <staff-tuning line=\"2\">\n"
				+ "            <tuning-step>A</tuning-step>\n"
				+ "            <tuning-octave>2</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "          <staff-tuning line=\"3\">\n"
				+ "            <tuning-step>D</tuning-step>\n"
				+ "            <tuning-octave>3</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "          <staff-tuning line=\"4\">\n"
				+ "            <tuning-step>G</tuning-step>\n"
				+ "            <tuning-octave>3</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "          <staff-tuning line=\"5\">\n"
				+ "            <tuning-step>B</tuning-step>\n"
				+ "            <tuning-octave>3</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "          <staff-tuning line=\"6\">\n"
				+ "            <tuning-step>E</tuning-step>\n"
				+ "            <tuning-octave>4</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "        </staff-details>\n"
				+ "      </attributes>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>E</step>\n"
				+ "          <octave>2</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>6</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>B</step>\n"
				+ "          <octave>2</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>5</string>\n"
				+ "            <fret>2</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>E</step>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>4</string>\n"
				+ "            <fret>2</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>G</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>3</string>\n"
				+ "            <fret>1</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>B</step>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>2</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>E</step>\n"
				+ "          <octave>4</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>1</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>B</step>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>2</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>G</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>3</string>\n"
				+ "            <fret>1</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "    </measure>\n"
				+ "    <measure number=\"2\">\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>E</step>\n"
				+ "          <octave>2</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>8</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>whole</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>6</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>B</step>\n"
				+ "          <octave>2</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>8</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>whole</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>5</string>\n"
				+ "            <fret>2</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>E</step>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>8</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>whole</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>4</string>\n"
				+ "            <fret>2</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>G</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>8</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>whole</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>3</string>\n"
				+ "            <fret>1</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>B</step>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>8</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>whole</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>2</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>E</step>\n"
				+ "          <octave>4</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>8</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>whole</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>1</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "    </measure>\n"
				+ "    <measure number=\"3\">\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>E</step>\n"
				+ "          <octave>2</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>6</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>B</step>\n"
				+ "          <octave>2</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>5</string>\n"
				+ "            <fret>2</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>E</step>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>4</string>\n"
				+ "            <fret>2</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>G</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>3</string>\n"
				+ "            <fret>1</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>B</step>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>2</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>E</step>\n"
				+ "          <octave>4</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>1</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>B</step>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>2</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>G</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>3</string>\n"
				+ "            <fret>1</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "    </measure>\n"
				+ "    <measure number=\"4\">\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>E</step>\n"
				+ "          <octave>2</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>8</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>whole</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>6</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>B</step>\n"
				+ "          <octave>2</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>8</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>whole</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>5</string>\n"
				+ "            <fret>2</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>E</step>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>8</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>whole</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>4</string>\n"
				+ "            <fret>2</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>G</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>8</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>whole</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>3</string>\n"
				+ "            <fret>1</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>B</step>\n"
				+ "          <octave>3</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>8</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>whole</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>2</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>E</step>\n"
				+ "          <octave>4</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>8</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>whole</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>1</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <barline location=\"right\">\n"
				+ "        <bar-style>light-heavy</bar-style>\n"
				+ "      </barline>\n"
				+ "    </measure>\n"
				+ "  </part>\n"
				+ "</score-partwise>\n"
				+ "";
		
		// remove whitespace characters
		actual = actual.replaceAll("\\s+","");
		expected = expected.replaceAll("\\s+","");
		
		assertEquals(expected, actual);
	}
	
	@Test
	public void bassTabToXMLTest1() {
		ArrayList<String> tabAsList = App.getFileList(
				"|-----------0-----|-0---------------|\n"
				+ "|---------0---0---|-0---------------|\n"
				+ "|-------1-------1-|-1---------------|\n"
				+ "|-----2-----------|-2---------------|\n");
		String actual = App.bassTabToXML(tabAsList);
		String expected = "<score-partwise version=\"3.1\">\n"
				+ "  <part-list>\n"
				+ "    <score-part id=\"P1\">\n"
				+ "      <part-name>Bass Guitar</part-name>\n"
				+ "    </score-part>\n"
				+ "  </part-list>\n"
				+ "  <part id=\"P1\">\n"
				+ "    <measure number=\"1\">\n"
				+ "      <attributes>\n"
				+ "        <divisions>2</divisions>\n"
				+ "        <key>\n"
				+ "          <fifths>0</fifths>\n"
				+ "        </key>\n"
				+ "        <time>\n"
				+ "          <beats>4</beats>\n"
				+ "          <beat-type>4</beat-type>\n"
				+ "        </time>\n"
				+ "        <clef>\n"
				+ "          <sign>TAB</sign>\n"
				+ "          <line>2</line>\n"
				+ "        </clef>\n"
				+ "        <staff-details>\n"
				+ "          <staff-lines>4</staff-lines>\n"
				+ "          <staff-tuning line=\"1\">\n"
				+ "            <tuning-step>E</tuning-step>\n"
				+ "            <tuning-octave>1</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "          <staff-tuning line=\"2\">\n"
				+ "            <tuning-step>A</tuning-step>\n"
				+ "            <tuning-octave>1</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "          <staff-tuning line=\"3\">\n"
				+ "            <tuning-step>D</tuning-step>\n"
				+ "            <tuning-octave>2</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "          <staff-tuning line=\"4\">\n"
				+ "            <tuning-step>G</tuning-step>\n"
				+ "            <tuning-octave>3</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "        </staff-details>\n"
				+ "      </attributes>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>F</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>4</string>\n"
				+ "            <fret>2</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>A</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>3</string>\n"
				+ "            <fret>1</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>D</step>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>2</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>G</step>\n"
				+ "          <octave>2</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>1</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>D</step>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>2</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>A</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>2</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>quarter</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>3</string>\n"
				+ "            <fret>1</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>F</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>4</string>\n"
				+ "            <fret>2</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>A</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>3</string>\n"
				+ "            <fret>1</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>D</step>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>2</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>G</step>\n"
				+ "          <octave>2</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>1</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <barline location=\"right\">\n"
				+ "        <bar-style>light-heavy</bar-style>\n"
				+ "      </barline>\n"
				+ "    </measure>\n"
				+ "  </part>\n"
				+ "</score-partwise>\n"
				+ "";
		
		// remove whitespace characters
		actual = actual.replaceAll("\\s+","");
		expected = expected.replaceAll("\\s+","");
		
		assertEquals(expected, actual);
	}
	
	@Test
	public void bassTabToXMLTest2() {
		ArrayList<String> tabAsList = App.getFileList(
				"|-----------0-----|-0---------------|\n"
				+ "|---------0---0---|-0---------------|\n"
				+ "|-------1-------1-|-1---------------|\n"
				+ "|-----2-----------|-2---------------|\n"
				+ "\n"
				+ "|-----------0-----|-0---------------|\n"
				+ "|---------0---0---|-0---------------|\n"
				+ "|-------1-------1-|-1---------------|\n"
				+ "|-----2-----------|-2---------------|");
		String actual = App.bassTabToXML(tabAsList);
		String expected = "<score-partwise version=\"3.1\">\n"
				+ "  <part-list>\n"
				+ "    <score-part id=\"P1\">\n"
				+ "      <part-name>Bass Guitar</part-name>\n"
				+ "    </score-part>\n"
				+ "  </part-list>\n"
				+ "  <part id=\"P1\">\n"
				+ "    <measure number=\"1\">\n"
				+ "      <attributes>\n"
				+ "        <divisions>2</divisions>\n"
				+ "        <key>\n"
				+ "          <fifths>0</fifths>\n"
				+ "        </key>\n"
				+ "        <time>\n"
				+ "          <beats>4</beats>\n"
				+ "          <beat-type>4</beat-type>\n"
				+ "        </time>\n"
				+ "        <clef>\n"
				+ "          <sign>TAB</sign>\n"
				+ "          <line>2</line>\n"
				+ "        </clef>\n"
				+ "        <staff-details>\n"
				+ "          <staff-lines>4</staff-lines>\n"
				+ "          <staff-tuning line=\"1\">\n"
				+ "            <tuning-step>E</tuning-step>\n"
				+ "            <tuning-octave>1</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "          <staff-tuning line=\"2\">\n"
				+ "            <tuning-step>A</tuning-step>\n"
				+ "            <tuning-octave>1</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "          <staff-tuning line=\"3\">\n"
				+ "            <tuning-step>D</tuning-step>\n"
				+ "            <tuning-octave>2</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "          <staff-tuning line=\"4\">\n"
				+ "            <tuning-step>2</tuning-step>\n"
				+ "            <tuning-octave>3</tuning-octave>\n"
				+ "          </staff-tuning>\n"
				+ "        </staff-details>\n"
				+ "      </attributes>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>F</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>4</string>\n"
				+ "            <fret>2</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>A</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>3</string>\n"
				+ "            <fret>1</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>D</step>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>2</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>G</step>\n"
				+ "          <octave>2</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>1</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>D</step>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>2</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>A</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>2</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>quarter</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>3</string>\n"
				+ "            <fret>1</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>F</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>4</string>\n"
				+ "            <fret>2</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>A</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>3</string>\n"
				+ "            <fret>1</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>D</step>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>2</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>G</step>\n"
				+ "          <octave>2</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>1</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "    </measure>\n"
				+ "    <measure number=\"2\">\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>F</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>4</string>\n"
				+ "            <fret>2</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>A</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>3</string>\n"
				+ "            <fret>1</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>D</step>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>2</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>G</step>\n"
				+ "          <octave>2</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>1</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>D</step>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>2</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>A</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>2</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>quarter</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>3</string>\n"
				+ "            <fret>1</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <pitch>\n"
				+ "          <step>F</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>4</string>\n"
				+ "            <fret>2</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>A</step>\n"
				+ "          <alter>1</alter>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>3</string>\n"
				+ "            <fret>1</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>D</step>\n"
				+ "          <octave>1</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>2</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <pitch>\n"
				+ "          <step>G</step>\n"
				+ "          <octave>2</octave>\n"
				+ "        </pitch>\n"
				+ "        <duration>1</duration>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <notations>\n"
				+ "          <technical>\n"
				+ "            <string>1</string>\n"
				+ "            <fret>0</fret>\n"
				+ "          </technical>\n"
				+ "        </notations>\n"
				+ "      </note>\n"
				+ "      <barline location=\"right\">\n"
				+ "        <bar-style>light-heavy</bar-style>\n"
				+ "      </barline>\n"
				+ "    </measure>\n"
				+ "  </part>\n"
				+ "</score-partwise>\n"
				+ "";
		
		// remove whitespace characters
		actual = actual.replaceAll("\\s+","");
		expected = expected.replaceAll("\\s+","");
		
		assertEquals(expected, actual);
	}
	
	@Test
	public void drumTabToXMLTest1() {
		ArrayList<String> tabAsList = App.getFileList(
				"CC|x---------------|--------x-------|\n"
				+ "HH|--x-x-x-x-x-x-x-|----------------|\n"
				+ "SD|----o-------o---|oooo------------|\n"
				+ "HT|----------------|----oo----------|\n"
				+ "MT|----------------|------oo--------|\n"
				+ "BD|o-------o-------|o-------o-------|");
		String actual = App.drumTabToXML(tabAsList);
		String expected = "<score-partwise version=\"3.1\">\n"
				+ "  <part-list>\n"
				+ "    <score-part id=\"P1\">\n"
				+ "      <part-name>Drumset</part-name>\n"
				+ "      <score-instrument id=\"P1-I36\">\n"
				+ "        <instrument-name>Bass Drum 1</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I37\">\n"
				+ "        <instrument-name>Bass Drum 2</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I38\">\n"
				+ "        <instrument-name>Side Stick</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I39\">\n"
				+ "        <instrument-name>Snare</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I42\">\n"
				+ "        <instrument-name>Low Floor Tom</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I43\">\n"
				+ "        <instrument-name>Closed Hi-Hat</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I44\">\n"
				+ "        <instrument-name>High Floor Tom</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I45\">\n"
				+ "        <instrument-name>Pedal Hi-Hat</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I46\">\n"
				+ "        <instrument-name>Low Tom</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I47\">\n"
				+ "        <instrument-name>Open Hi-Hat</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I48\">\n"
				+ "        <instrument-name>Low-Mid Tom</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I49\">\n"
				+ "        <instrument-name>Hi-Mid Tom</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I50\">\n"
				+ "        <instrument-name>Crash Cymbal 1</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I51\">\n"
				+ "        <instrument-name>High Tom</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I52\">\n"
				+ "        <instrument-name>Ride Cymbal 1</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I53\">\n"
				+ "        <instrument-name>Chinese Cymbal</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I54\">\n"
				+ "        <instrument-name>Ride Bell</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I55\">\n"
				+ "        <instrument-name>Tambourine</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I56\">\n"
				+ "        <instrument-name>Splash Cymbal</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I57\">\n"
				+ "        <instrument-name>Cowbell</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I58\">\n"
				+ "        <instrument-name>Crash Cymbal 2</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I60\">\n"
				+ "        <instrument-name>Ride Cymbal 2</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I64\">\n"
				+ "        <instrument-name>Open Hi Conga</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      <score-instrument id=\"P1-I65\">\n"
				+ "        <instrument-name>Low Conga</instrument-name>\n"
				+ "        </score-instrument>\n"
				+ "      </score-part>\n"
				+ "    </part-list>\n"
				+ "  <part id=\"P1\">\n"
				+ "    <measure number=\"1\">\n"
				+ "      <attributes>\n"
				+ "        <divisions>4</divisions>\n"
				+ "        <key>\n"
				+ "          <fifths>0</fifths>\n"
				+ "          </key>\n"
				+ "        <time>\n"
				+ "          <beats>4</beats>\n"
				+ "          <beat-type>4</beat-type>\n"
				+ "          </time>\n"
				+ "        <clef>\n"
				+ "          <sign>percussion</sign>\n"
				+ "          <line>2</line>\n"
				+ "          </clef>\n"
				+ "        </attributes>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>A</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>2</duration>\n"
				+ "        <instrument id=\"P1-I50\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <notehead>x</notehead>\n"
				+ "        <beam number=\"1\">begin</beam>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>G</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>2</duration>\n"
				+ "        <instrument id=\"P1-I43\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <notehead>x</notehead>\n"
				+ "        <beam number=\"1\">continue</beam>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>C</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>2</duration>\n"
				+ "        <instrument id=\"P1-I39\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <beam number=\"1\">continue</beam>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>G</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>2</duration>\n"
				+ "        <instrument id=\"P1-I43\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <notehead>x</notehead>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>G</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>2</duration>\n"
				+ "        <instrument id=\"P1-I43\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <notehead>x</notehead>\n"
				+ "        <beam number=\"1\">end</beam>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>G</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>2</duration>\n"
				+ "        <instrument id=\"P1-I43\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <notehead>x</notehead>\n"
				+ "        <beam number=\"1\">begin</beam>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>G</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>2</duration>\n"
				+ "        <instrument id=\"P1-I43\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <notehead>x</notehead>\n"
				+ "        <beam number=\"1\">continue</beam>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>C</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>2</duration>\n"
				+ "        <instrument id=\"P1-I39\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <beam number=\"1\">continue</beam>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <chord/>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>G</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>2</duration>\n"
				+ "        <instrument id=\"P1-I43\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <notehead>x</notehead>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>G</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>2</duration>\n"
				+ "        <instrument id=\"P1-I43\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>eighth</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <notehead>x</notehead>\n"
				+ "        <beam number=\"1\">end</beam>\n"
				+ "        </note>\n"
				+ "      <backup>\n"
				+ "        <duration>16</duration>\n"
				+ "        </backup>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>F</display-step>\n"
				+ "          <display-octave>4</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>8</duration>\n"
				+ "        <instrument id=\"P1-I36\"/>\n"
				+ "        <voice>2</voice>\n"
				+ "        <type>half</type>\n"
				+ "        <stem>down</stem>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>F</display-step>\n"
				+ "          <display-octave>4</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>8</duration>\n"
				+ "        <instrument id=\"P1-I36\"/>\n"
				+ "        <voice>2</voice>\n"
				+ "        <type>half</type>\n"
				+ "        <stem>down</stem>\n"
				+ "        </note>\n"
				+ "      </measure>\n"
				+ "    <measure number=\"2\">\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>C</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>1</duration>\n"
				+ "        <instrument id=\"P1-I39\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>16th</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <beam number=\"1\">begin</beam>\n"
				+ "        <beam number=\"2\">begin</beam>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>C</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>1</duration>\n"
				+ "        <instrument id=\"P1-I39\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>16th</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <beam number=\"1\">continue</beam>\n"
				+ "        <beam number=\"2\">continue</beam>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>C</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>1</duration>\n"
				+ "        <instrument id=\"P1-I39\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>16th</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <beam number=\"1\">continue</beam>\n"
				+ "        <beam number=\"2\">continue</beam>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>C</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>1</duration>\n"
				+ "        <instrument id=\"P1-I39\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>16th</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <beam number=\"1\">end</beam>\n"
				+ "        <beam number=\"2\">end</beam>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>E</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>1</duration>\n"
				+ "        <instrument id=\"P1-I48\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>16th</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <beam number=\"1\">begin</beam>\n"
				+ "        <beam number=\"2\">begin</beam>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>E</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>1</duration>\n"
				+ "        <instrument id=\"P1-I48\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>16th</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <beam number=\"1\">continue</beam>\n"
				+ "        <beam number=\"2\">continue</beam>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>D</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>1</duration>\n"
				+ "        <instrument id=\"P1-I46\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>16th</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <beam number=\"1\">continue</beam>\n"
				+ "        <beam number=\"2\">continue</beam>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>D</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>1</duration>\n"
				+ "        <instrument id=\"P1-I46\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>16th</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <beam number=\"1\">end</beam>\n"
				+ "        <beam number=\"2\">end</beam>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>A</display-step>\n"
				+ "          <display-octave>5</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>8</duration>\n"
				+ "        <instrument id=\"P1-I50\"/>\n"
				+ "        <voice>1</voice>\n"
				+ "        <type>half</type>\n"
				+ "        <stem>up</stem>\n"
				+ "        <notehead>x</notehead>\n"
				+ "        </note>\n"
				+ "      <backup>\n"
				+ "        <duration>16</duration>\n"
				+ "        </backup>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>F</display-step>\n"
				+ "          <display-octave>4</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>4</duration>\n"
				+ "        <instrument id=\"P1-I36\"/>\n"
				+ "        <voice>2</voice>\n"
				+ "        <type>quarter</type>\n"
				+ "        <stem>down</stem>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <rest/>\n"
				+ "        <duration>4</duration>\n"
				+ "        <voice>2</voice>\n"
				+ "        <type>quarter</type>\n"
				+ "        </note>\n"
				+ "      <note>\n"
				+ "        <unpitched>\n"
				+ "          <display-step>F</display-step>\n"
				+ "          <display-octave>4</display-octave>\n"
				+ "          </unpitched>\n"
				+ "        <duration>8</duration>\n"
				+ "        <instrument id=\"P1-I36\"/>\n"
				+ "        <voice>2</voice>\n"
				+ "        <type>half</type>\n"
				+ "        <stem>down</stem>\n"
				+ "        </note>\n"
				+ "      <barline location=\"right\">\n"
				+ "        <bar-style>light-heavy</bar-style>\n"
				+ "        </barline>\n"
				+ "      </measure>\n"
				+ "    </part>\n"
				+ "  </score-partwise>";
		
		actual = actual.replaceAll("\\s+","");
		expected = expected.replaceAll("\\s+","");
		
		assertEquals(expected, actual);
	}
	
	@Test
	public void drumTabToXMLTest2() {
		ArrayList<String> tabAsList = App.getFileList(
				"CC|x---------------|--------x-------|\n"
				+ "HH|--x-x-x-x-x-x-x-|----------------|\n"
				+ "SD|----o-------o---|oooo------------|\n"
				+ "HT|----------------|----oo----------|\n"
				+ "MT|----------------|------oo--------|\n"
				+ "BD|o-------o-------|o-------o-------|\n"
				+ "\n"
				+ "CC|x---------------|--------x-------|\n"
				+ "HH|--x-x-x-x-x-x-x-|----------------|\n"
				+ "SD|----o-------o---|oooo------------|\n"
				+ "HT|----------------|----oo----------|\n"
				+ "MT|----------------|------oo--------|\n"
				+ "BD|o-------o-------|o-------o-------|");
		String actual = App.drumTabToXML(tabAsList);
		String expected = "";
		
		actual = actual.replaceAll("\\s+","");
		expected = expected.replaceAll("\\s+","");
		
		assertEquals(true, true);
	}

}
